"""empty message

Revision ID: e6cd42490fc0
Revises: 07258617c487
Create Date: 2018-11-14 16:09:11.652827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6cd42490fc0'
down_revision = '07258617c487'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story', sa.String(), nullable=True),
    sa.Column('uploaded', sa.DateTime(), nullable=True),
    sa.Column('large', sa.String(), nullable=True),
    sa.Column('thumbnail', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###
